const D = {
  meta: {
    title: '数据资源管理平台 · GDEPDI 海上风电',
    subtitle: '数据资产目录 · 数据治理看板 —— 设计态/生产态两态分层的治理闭环演示',
    disclaimer: '⚠ 参考模型声明：基于广东院公开业务信息构建的演示模型，非广东院实际部署、仅供演示。不虚构内部运营数据。',
    stats: { applications: 5, databases: 5, tables: 10, fields: 51, rules: 8, standards: 6, masterData: 5 },
  },
  applications: [
    { id: 'app_res', name: '风资源评估系统', desc: '测风/气象数据采集与分析' },
    { id: 'app_survey', name: '海洋勘测系统', desc: '地质/测绘/岩土数据' },
    { id: 'app_design', name: '工程设计系统', desc: '风机/海缆/升压站设计' },
    { id: 'app_build', name: '施工管理系统', desc: '船机调度/作业进度' },
    { id: 'app_ops', name: '智慧运维系统', desc: 'SCADA 遥测/功率预测/备件' },
  ],
  databases: [
    { id: 'db_res', appId: 'app_res', name: '资源评估库' },
    { id: 'db_survey', appId: 'app_survey', name: '勘测库' },
    { id: 'db_design', appId: 'app_design', name: '设计库' },
    { id: 'db_build', appId: 'app_build', name: '施工库' },
    { id: 'db_ops', appId: 'app_ops', name: '运维库' },
  ],
  bizDomains: [
    { id: 'bd_resource', name: '资源评估域', subjects: [{ id: 'bs_wind', name: '测风' }] },
    { id: 'bd_survey', name: '勘测域', subjects: [{ id: 'bs_geo', name: '地质' }, { id: 'bs_topo', name: '测绘' }] },
    { id: 'bd_design', name: '设计域', subjects: [{ id: 'bs_device', name: '设备设计' }] },
    { id: 'bd_build', name: '工程建设域', subjects: [{ id: 'bs_schedule', name: '进度' }] },
    { id: 'bd_ops', name: '生产运营域', subjects: [{ id: 'bs_scada', name: '遥测' }, { id: 'bs_forecast', name: '功率预测' }, { id: 'bs_spare', name: '备件' }] },
  ],
  security: [
    { level: 'L1', name: '公开', desc: '可对外公开', mask: null },
    { level: 'L2', name: '内部', desc: '企业内部共享', mask: null },
    { level: 'L3', name: '敏感', desc: '受限共享，脱敏后使用', mask: '字段掩码/坐标偏移' },
    { level: 'L4', name: '涉密', desc: '涉密，导出受管控', mask: '坐标模糊化' },
  ],
  masterData: [
    { id: 'md_turbine', code: 'WTG-0001', entityType: '风机', name: 'MySE16-260', attrs: { 额定功率: '16MW', 叶轮直径: '260m' } },
    { id: 'md_cable', code: 'CBL-0001', entityType: '海缆', name: '500kV 三芯海缆', attrs: { 电压等级: '500kV', 截面: '1800mm²' } },
    { id: 'md_substation', code: 'SS-0001', entityType: '升压站', name: '青洲一二 500kV 海上升压站', attrs: { 主变容量: '2×450MVA', 接线方式: '四层甲板' } },
    { id: 'md_project', code: 'PRJ-0001', entityType: '项目', name: '阳江青洲一、二', attrs: { 规模: '1000MW', 阶段: '运维' } },
    { id: 'md_supplier', code: 'SUP-0001', entityType: '供应商', name: '明阳智能', attrs: { 资质: '整机商', 供货范围: '风机' } },
  ],
  standards: [
    { id: 'std_voltage', code: 'DL-01', name: '电压等级', kind: 'code', values: ['35kV', '66kV', '220kV', '500kV', '±500kV'] },
    { id: 'std_turbine', code: 'DL-02', name: '风机机型', kind: 'code', values: ['8MW', '12MW', '16MW', '16.6MW漂浮式'] },
    { id: 'std_foundation', code: 'DL-03', name: '基础型式', kind: 'code', values: ['单桩', '导管架', '多桩', '漂浮式'] },
    { id: 'std_sea_area', code: 'DL-04', name: '海域编码', kind: 'code', values: ['粤东', '粤西', '珠三角'] },
    { id: 'std_cable', code: 'DL-05', name: '海缆类型', kind: 'code', values: ['集电', '送出', '三芯', '单芯'] },
    { id: 'std_power', code: 'FD-01', name: '有功功率字段标准', kind: 'field', fieldStd: { name: 'active_power', type: 'decimal(5,2)', unit: 'MW', domain: '0~16' } },
  ],
  qualityRules: [
    { id: 'qr_001', name: 'SCADA 有功功率取值范围', type: '准确性', targetFieldId: 'f_scada_power', expr: '0 <= active_power <= 16', threshold: '100%', severity: '严重', status: '启用' },
    { id: 'qr_002', name: '测风风速取值越界', type: '准确性', targetFieldId: 'f_wind_speed', expr: '0 <= wind_speed <= 70', threshold: '100%', severity: '警告', status: '启用' },
    { id: 'qr_003', name: '测风数据完整性', type: '完整性', targetFieldId: 'f_wind_speed', expr: '风速字段非空率 >= 95%', threshold: '95%', severity: '警告', status: '启用' },
    { id: 'qr_004', name: '海缆监测温度一致性', type: '一致性', targetFieldId: 'f_cable_temp', expr: '温度与相邻测点偏差 <= 5℃', threshold: '100%', severity: '严重', status: '启用' },
    { id: 'qr_005', name: '功率预测及时性', type: '及时性', targetFieldId: 'f_forecast_time', expr: '预测结果产出延迟 <= 15min', threshold: '15min', severity: '提示', status: '启用' },
    { id: 'qr_006', name: '地质钻孔地层字段完整性', type: '完整性', targetFieldId: 'f_geo_stratum', expr: '地层编号非空率 = 100%', threshold: '100%', severity: '警告', status: '启用' },
    { id: 'qr_007', name: '主变油温阈值', type: '准确性', targetFieldId: 'f_sub_oil_temp', expr: '0 <= oil_temp <= 105', threshold: '100%', severity: '严重', status: '启用' },
    { id: 'qr_008', name: '备品备件库存准确性', type: '准确性', targetFieldId: 'f_spare_qty', expr: '库存数量 >= 0', threshold: '100%', severity: '提示', status: '启用' },
  ],
  tables: [
    { id: 't_wind', appId: 'app_res', dbId: 'db_res', nameCn: '测风数据表', nameEn: 'wind_measurement', tableType: '业务表', bizDomainId: 'bd_resource', subjectId: 'bs_wind', masterDataId: null, desc: '测风塔实测风速/风向/湍流' },
    { id: 't_geo', appId: 'app_survey', dbId: 'db_survey', nameCn: '地质钻孔表', nameEn: 'geological_borehole', tableType: '业务表', bizDomainId: 'bd_survey', subjectId: 'bs_geo', masterDataId: null, desc: '海上风电场地地质钻孔与岩土地层信息' },
    { id: 't_topo', appId: 'app_survey', dbId: 'db_survey', nameCn: '海底地形测绘表', nameEn: 'seabed_topography', tableType: '业务表', bizDomainId: 'bd_survey', subjectId: 'bs_topo', masterDataId: null, desc: '海底地形测绘坐标、水深与海缆路由' },
    { id: 't_turbine', appId: 'app_design', dbId: 'db_design', nameCn: '风机设备表', nameEn: 'turbine_device', tableType: '业务表', bizDomainId: 'bd_design', subjectId: 'bs_device', masterDataId: 'md_turbine', desc: '风机机型、额定功率与基础型式等设备参数' },
    { id: 't_cable', appId: 'app_design', dbId: 'db_design', nameCn: '海缆参数表', nameEn: 'submarine_cable', tableType: '业务表', bizDomainId: 'bd_design', subjectId: 'bs_device', masterDataId: 'md_cable', desc: '海缆类型、电压等级与监测温度等参数' },
    { id: 't_substation', appId: 'app_design', dbId: 'db_design', nameCn: '升压站主变表', nameEn: 'substation_transformer', tableType: '业务表', bizDomainId: 'bd_design', subjectId: 'bs_device', masterDataId: 'md_substation', desc: '海上升压站主变容量、电压与油温参数' },
    { id: 't_progress', appId: 'app_build', dbId: 'db_build', nameCn: '作业进度表', nameEn: 'construction_progress', tableType: '业务表', bizDomainId: 'bd_build', subjectId: 'bs_schedule', masterDataId: 'md_project', desc: '船机调度与施工作业进度记录' },
    { id: 't_scada', appId: 'app_ops', dbId: 'db_ops', nameCn: 'SCADA 遥测表', nameEn: 'scada_telemetry', tableType: '技术表', bizDomainId: 'bd_ops', subjectId: 'bs_scada', masterDataId: null, desc: '风机 SCADA 遥测数据（功率/温度/振动）' },
    { id: 't_forecast', appId: 'app_ops', dbId: 'db_ops', nameCn: '功率预测结果表', nameEn: 'power_forecast', tableType: '业务表', bizDomainId: 'bd_ops', subjectId: 'bs_forecast', masterDataId: 'md_project', desc: '功率预测结果与预测精度评估' },
    { id: 't_spare', appId: 'app_ops', dbId: 'db_ops', nameCn: '备品备件表', nameEn: 'spare_parts', tableType: '业务表', bizDomainId: 'bd_ops', subjectId: 'bs_spare', masterDataId: null, desc: '备品备件名称、库存与适配机型' },
  ],
  fields: [
    { id: 'f_wind_speed', tableId: 't_wind', seq: 1,
      business: { code: 'WIND_SPEED', nameCn: '风速', definition: '测风塔 100m 高度实测平均风速', masterDataId: null, masterDataType: null },
      technical: { type: 'decimal(5,2)', length: 7, isPK: false, isFK: false, qualityRuleIds: ['qr_002', 'qr_003'] },
      management: { standardId: null, securityLevel: 'L2', owner: '资源评估组', updateFrequency: '10分钟' } },
    { id: 'f_wind_dir', tableId: 't_wind', seq: 2,
      business: { code: 'WIND_DIR', nameCn: '风向', definition: '主导风向（0~360°）', masterDataId: null, masterDataType: null },
      technical: { type: 'smallint', length: 4, isPK: false, isFK: false, qualityRuleIds: [] },
      management: { standardId: null, securityLevel: 'L2', owner: '资源评估组', updateFrequency: '10分钟' } },
    { id: 'f_wind_turbulence', tableId: 't_wind', seq: 3,
      business: { code: 'TURBULENCE', nameCn: '湍流强度', definition: '湍流强度等级', masterDataId: null, masterDataType: null },
      technical: { type: 'varchar(10)', length: 10, isPK: false, isFK: false, qualityRuleIds: [] },
      management: { standardId: null, securityLevel: 'L2', owner: '资源评估组', updateFrequency: '10分钟' } },
    { id: 'f_wind_time', tableId: 't_wind', seq: 4,
      business: { code: 'MEASURE_TIME', nameCn: '测量时间', definition: '数据采集时间戳', masterDataId: null, masterDataType: null },
      technical: { type: 'datetime', length: 0, isPK: true, isFK: false, qualityRuleIds: [] },
      management: { standardId: null, securityLevel: 'L2', owner: '资源评估组', updateFrequency: '10分钟' } },
    { id: 'f_wind_project', tableId: 't_wind', seq: 5,
      business: { code: 'PROJECT_ID', nameCn: '所属项目', definition: '测风塔所属海上风电项目', masterDataId: 'md_project', masterDataType: '项目' },
      technical: { type: 'varchar(32)', length: 32, isPK: false, isFK: true, qualityRuleIds: [] },
      management: { standardId: null, securityLevel: 'L2', owner: '资源评估组', updateFrequency: '静态' } },

    // t_geo 地质钻孔表
    { id: 'f_geo_stratum', tableId: 't_geo', seq: 1,
      business: { code: 'STRATUM', nameCn: '地层编号', definition: '地层编号', masterDataId: null, masterDataType: null },
      technical: { type: 'varchar(20)', length: 20, isPK: true, isFK: false, qualityRuleIds: ['qr_006'] },
      management: { standardId: null, securityLevel: 'L3', owner: '勘测组', updateFrequency: '静态' } },
    { id: 'f_geo_depth', tableId: 't_geo', seq: 2,
      business: { code: 'DEPTH', nameCn: '钻孔深度', definition: '钻孔深度', masterDataId: null, masterDataType: null },
      technical: { type: 'decimal(6,1)', length: 7, isPK: false, isFK: false, qualityRuleIds: [] },
      management: { standardId: null, securityLevel: 'L3', owner: '勘测组', updateFrequency: '静态' } },
    { id: 'f_geo_soil', tableId: 't_geo', seq: 3,
      business: { code: 'SOIL_TYPE', nameCn: '土质类型', definition: '土质类型', masterDataId: null, masterDataType: null },
      technical: { type: 'varchar(20)', length: 20, isPK: false, isFK: false, qualityRuleIds: [] },
      management: { standardId: null, securityLevel: 'L3', owner: '勘测组', updateFrequency: '静态' } },
    { id: 'f_geo_bearing', tableId: 't_geo', seq: 4,
      business: { code: 'BEARING', nameCn: '桩基持力层', definition: '桩基持力层', masterDataId: null, masterDataType: null },
      technical: { type: 'varchar(20)', length: 20, isPK: false, isFK: false, qualityRuleIds: [] },
      management: { standardId: null, securityLevel: 'L3', owner: '勘测组', updateFrequency: '静态' } },
    { id: 'f_geo_project', tableId: 't_geo', seq: 5,
      business: { code: 'PROJECT_ID', nameCn: '所属项目', definition: '所属项目', masterDataId: 'md_project', masterDataType: '项目' },
      technical: { type: 'varchar(32)', length: 32, isPK: false, isFK: true, qualityRuleIds: [] },
      management: { standardId: null, securityLevel: 'L3', owner: '勘测组', updateFrequency: '静态' } },

    // t_topo 海底地形测绘表
    { id: 'f_topo_coord', tableId: 't_topo', seq: 1,
      business: { code: 'COORD', nameCn: '坐标', definition: '坐标', masterDataId: null, masterDataType: null },
      technical: { type: 'varchar(40)', length: 40, isPK: true, isFK: false, qualityRuleIds: [] },
      management: { standardId: 'std_sea_area', securityLevel: 'L4', owner: '测绘组', updateFrequency: '静态' } },
    { id: 'f_topo_depth', tableId: 't_topo', seq: 2,
      business: { code: 'WATER_DEPTH', nameCn: '水深', definition: '水深', masterDataId: null, masterDataType: null },
      technical: { type: 'decimal(6,1)', length: 7, isPK: false, isFK: false, qualityRuleIds: [] },
      management: { standardId: null, securityLevel: 'L3', owner: '测绘组', updateFrequency: '静态' } },
    { id: 'f_topo_survey', tableId: 't_topo', seq: 3,
      business: { code: 'SURVEY_DATE', nameCn: '测绘日期', definition: '测绘日期', masterDataId: null, masterDataType: null },
      technical: { type: 'date', length: 0, isPK: false, isFK: false, qualityRuleIds: [] },
      management: { standardId: null, securityLevel: 'L3', owner: '测绘组', updateFrequency: '静态' } },
    { id: 'f_topo_route', tableId: 't_topo', seq: 4,
      business: { code: 'CABLE_ROUTE', nameCn: '海缆路由', definition: '海缆路由', masterDataId: null, masterDataType: null },
      technical: { type: 'varchar(64)', length: 64, isPK: false, isFK: false, qualityRuleIds: [] },
      management: { standardId: null, securityLevel: 'L3', owner: '测绘组', updateFrequency: '静态' } },
    { id: 'f_topo_project', tableId: 't_topo', seq: 5,
      business: { code: 'PROJECT_ID', nameCn: '所属项目', definition: '所属项目', masterDataId: 'md_project', masterDataType: '项目' },
      technical: { type: 'varchar(32)', length: 32, isPK: false, isFK: true, qualityRuleIds: [] },
      management: { standardId: null, securityLevel: 'L3', owner: '测绘组', updateFrequency: '静态' } },

    // t_turbine 风机设备表
    { id: 'f_turbine_model', tableId: 't_turbine', seq: 1,
      business: { code: 'MODEL', nameCn: '机型', definition: '机型', masterDataId: null, masterDataType: null },
      technical: { type: 'varchar(20)', length: 20, isPK: false, isFK: false, qualityRuleIds: [] },
      management: { standardId: 'std_turbine', securityLevel: 'L2', owner: '设计组', updateFrequency: '静态' } },
    { id: 'f_turbine_md', tableId: 't_turbine', seq: 2,
      business: { code: 'MD_ID', nameCn: '主数据编码', definition: '主数据编码', masterDataId: 'md_turbine', masterDataType: '风机' },
      technical: { type: 'varchar(32)', length: 32, isPK: true, isFK: false, qualityRuleIds: [] },
      management: { standardId: null, securityLevel: 'L2', owner: '设计组', updateFrequency: '静态' } },
    { id: 'f_turbine_power', tableId: 't_turbine', seq: 3,
      business: { code: 'RATED_POWER', nameCn: '额定功率', definition: '额定功率', masterDataId: null, masterDataType: null },
      technical: { type: 'decimal(5,2)', length: 7, isPK: false, isFK: false, qualityRuleIds: [] },
      management: { standardId: 'std_power', securityLevel: 'L2', owner: '设计组', updateFrequency: '静态' } },
    { id: 'f_turbine_foundation', tableId: 't_turbine', seq: 4,
      business: { code: 'FOUNDATION', nameCn: '基础型式', definition: '基础型式', masterDataId: null, masterDataType: null },
      technical: { type: 'varchar(20)', length: 20, isPK: false, isFK: false, qualityRuleIds: [] },
      management: { standardId: 'std_foundation', securityLevel: 'L2', owner: '设计组', updateFrequency: '静态' } },
    { id: 'f_turbine_supplier', tableId: 't_turbine', seq: 5,
      business: { code: 'SUPPLIER_ID', nameCn: '供应商', definition: '供应商', masterDataId: 'md_supplier', masterDataType: '供应商' },
      technical: { type: 'varchar(32)', length: 32, isPK: false, isFK: true, qualityRuleIds: [] },
      management: { standardId: null, securityLevel: 'L2', owner: '设计组', updateFrequency: '静态' } },
    { id: 'f_turbine_project', tableId: 't_turbine', seq: 6,
      business: { code: 'PROJECT_ID', nameCn: '所属项目', definition: '所属项目', masterDataId: 'md_project', masterDataType: '项目' },
      technical: { type: 'varchar(32)', length: 32, isPK: false, isFK: true, qualityRuleIds: [] },
      management: { standardId: null, securityLevel: 'L2', owner: '设计组', updateFrequency: '静态' } },

    // t_cable 海缆参数表
    { id: 'f_cable_type', tableId: 't_cable', seq: 1,
      business: { code: 'TYPE', nameCn: '海缆类型', definition: '海缆类型', masterDataId: null, masterDataType: null },
      technical: { type: 'varchar(20)', length: 20, isPK: false, isFK: false, qualityRuleIds: [] },
      management: { standardId: 'std_cable', securityLevel: 'L3', owner: '设计组', updateFrequency: '静态' } },
    { id: 'f_cable_md', tableId: 't_cable', seq: 2,
      business: { code: 'MD_ID', nameCn: '主数据编码', definition: '主数据编码', masterDataId: 'md_cable', masterDataType: '海缆' },
      technical: { type: 'varchar(32)', length: 32, isPK: true, isFK: false, qualityRuleIds: [] },
      management: { standardId: null, securityLevel: 'L3', owner: '设计组', updateFrequency: '静态' } },
    { id: 'f_cable_voltage', tableId: 't_cable', seq: 3,
      business: { code: 'VOLTAGE', nameCn: '电压等级', definition: '电压等级', masterDataId: null, masterDataType: null },
      technical: { type: 'varchar(10)', length: 10, isPK: false, isFK: false, qualityRuleIds: [] },
      management: { standardId: 'std_voltage', securityLevel: 'L3', owner: '设计组', updateFrequency: '静态' } },
    { id: 'f_cable_temp', tableId: 't_cable', seq: 4,
      business: { code: 'MONITOR_TEMP', nameCn: '监测温度', definition: '监测温度', masterDataId: null, masterDataType: null },
      technical: { type: 'decimal(5,1)', length: 6, isPK: false, isFK: false, qualityRuleIds: ['qr_004'] },
      management: { standardId: null, securityLevel: 'L3', owner: '设计组', updateFrequency: '静态' } },
    { id: 'f_cable_route', tableId: 't_cable', seq: 5,
      business: { code: 'ROUTE', nameCn: '路由坐标', definition: '路由坐标', masterDataId: null, masterDataType: null },
      technical: { type: 'varchar(64)', length: 64, isPK: false, isFK: false, qualityRuleIds: [] },
      management: { standardId: null, securityLevel: 'L3', owner: '设计组', updateFrequency: '静态' } },

    // t_substation 升压站主变表
    { id: 'f_sub_md', tableId: 't_substation', seq: 1,
      business: { code: 'MD_ID', nameCn: '主数据编码', definition: '主数据编码', masterDataId: 'md_substation', masterDataType: '升压站' },
      technical: { type: 'varchar(32)', length: 32, isPK: true, isFK: false, qualityRuleIds: [] },
      management: { standardId: null, securityLevel: 'L2', owner: '设计组', updateFrequency: '静态' } },
    { id: 'f_sub_capacity', tableId: 't_substation', seq: 2,
      business: { code: 'CAPACITY', nameCn: '主变容量', definition: '主变容量', masterDataId: null, masterDataType: null },
      technical: { type: 'varchar(20)', length: 20, isPK: false, isFK: false, qualityRuleIds: [] },
      management: { standardId: null, securityLevel: 'L2', owner: '设计组', updateFrequency: '静态' } },
    { id: 'f_sub_voltage', tableId: 't_substation', seq: 3,
      business: { code: 'VOLTAGE', nameCn: '电压等级', definition: '电压等级', masterDataId: null, masterDataType: null },
      technical: { type: 'varchar(10)', length: 10, isPK: false, isFK: false, qualityRuleIds: [] },
      management: { standardId: 'std_voltage', securityLevel: 'L2', owner: '设计组', updateFrequency: '静态' } },
    { id: 'f_sub_oil_temp', tableId: 't_substation', seq: 4,
      business: { code: 'OIL_TEMP', nameCn: '油温', definition: '油温', masterDataId: null, masterDataType: null },
      technical: { type: 'decimal(5,1)', length: 6, isPK: false, isFK: false, qualityRuleIds: ['qr_007'] },
      management: { standardId: null, securityLevel: 'L2', owner: '设计组', updateFrequency: '静态' } },
    { id: 'f_sub_project', tableId: 't_substation', seq: 5,
      business: { code: 'PROJECT_ID', nameCn: '所属项目', definition: '所属项目', masterDataId: 'md_project', masterDataType: '项目' },
      technical: { type: 'varchar(32)', length: 32, isPK: false, isFK: true, qualityRuleIds: [] },
      management: { standardId: null, securityLevel: 'L2', owner: '设计组', updateFrequency: '静态' } },

    // t_progress 作业进度表
    { id: 'f_prog_task', tableId: 't_progress', seq: 1,
      business: { code: 'TASK', nameCn: '作业任务', definition: '作业任务', masterDataId: null, masterDataType: null },
      technical: { type: 'varchar(64)', length: 64, isPK: true, isFK: false, qualityRuleIds: [] },
      management: { standardId: null, securityLevel: 'L2', owner: '施工管理组', updateFrequency: '每日' } },
    { id: 'f_prog_progress', tableId: 't_progress', seq: 2,
      business: { code: 'PROGRESS', nameCn: '进度百分比', definition: '进度百分比', masterDataId: null, masterDataType: null },
      technical: { type: 'tinyint', length: 1, isPK: false, isFK: false, qualityRuleIds: [] },
      management: { standardId: null, securityLevel: 'L2', owner: '施工管理组', updateFrequency: '每日' } },
    { id: 'f_prog_vessel', tableId: 't_progress', seq: 3,
      business: { code: 'VESSEL', nameCn: '船机', definition: '船机', masterDataId: null, masterDataType: null },
      technical: { type: 'varchar(32)', length: 32, isPK: false, isFK: false, qualityRuleIds: [] },
      management: { standardId: null, securityLevel: 'L2', owner: '施工管理组', updateFrequency: '每日' } },
    { id: 'f_prog_seastate', tableId: 't_progress', seq: 4,
      business: { code: 'SEA_STATE', nameCn: '海况', definition: '海况', masterDataId: null, masterDataType: null },
      technical: { type: 'varchar(20)', length: 20, isPK: false, isFK: false, qualityRuleIds: [] },
      management: { standardId: null, securityLevel: 'L2', owner: '施工管理组', updateFrequency: '每日' } },
    { id: 'f_prog_project', tableId: 't_progress', seq: 5,
      business: { code: 'PROJECT_ID', nameCn: '所属项目', definition: '所属项目', masterDataId: 'md_project', masterDataType: '项目' },
      technical: { type: 'varchar(32)', length: 32, isPK: false, isFK: true, qualityRuleIds: [] },
      management: { standardId: null, securityLevel: 'L2', owner: '施工管理组', updateFrequency: '每日' } },

    // t_scada SCADA 遥测表
    { id: 'f_scada_power', tableId: 't_scada', seq: 1,
      business: { code: 'ACTIVE_POWER', nameCn: '有功功率', definition: '有功功率', masterDataId: null, masterDataType: null },
      technical: { type: 'decimal(5,2)', length: 7, isPK: false, isFK: false, qualityRuleIds: ['qr_001'] },
      management: { standardId: 'std_power', securityLevel: 'L2', owner: '运维组', updateFrequency: '1分钟' } },
    { id: 'f_scada_turbine', tableId: 't_scada', seq: 2,
      business: { code: 'TURBINE_ID', nameCn: '机组', definition: '机组', masterDataId: 'md_turbine', masterDataType: '风机' },
      technical: { type: 'varchar(32)', length: 32, isPK: false, isFK: true, qualityRuleIds: [] },
      management: { standardId: null, securityLevel: 'L2', owner: '运维组', updateFrequency: '1分钟' } },
    { id: 'f_scada_temp', tableId: 't_scada', seq: 3,
      business: { code: 'TEMP', nameCn: '温度', definition: '温度', masterDataId: null, masterDataType: null },
      technical: { type: 'decimal(5,1)', length: 6, isPK: false, isFK: false, qualityRuleIds: [] },
      management: { standardId: null, securityLevel: 'L2', owner: '运维组', updateFrequency: '1分钟' } },
    { id: 'f_scada_vibration', tableId: 't_scada', seq: 4,
      business: { code: 'VIBRATION', nameCn: '振动', definition: '振动', masterDataId: null, masterDataType: null },
      technical: { type: 'decimal(6,2)', length: 8, isPK: false, isFK: false, qualityRuleIds: [] },
      management: { standardId: null, securityLevel: 'L2', owner: '运维组', updateFrequency: '1分钟' } },
    { id: 'f_scada_time', tableId: 't_scada', seq: 5,
      business: { code: 'TS', nameCn: '时间戳', definition: '时间戳', masterDataId: null, masterDataType: null },
      technical: { type: 'datetime', length: 0, isPK: true, isFK: false, qualityRuleIds: [] },
      management: { standardId: null, securityLevel: 'L2', owner: '运维组', updateFrequency: '1分钟' } },

    // t_forecast 功率预测结果表
    { id: 'f_forecast_time', tableId: 't_forecast', seq: 1,
      business: { code: 'FORECAST_TIME', nameCn: '预测时间', definition: '预测时间', masterDataId: null, masterDataType: null },
      technical: { type: 'datetime', length: 0, isPK: true, isFK: false, qualityRuleIds: ['qr_005'] },
      management: { standardId: null, securityLevel: 'L2', owner: '运维组', updateFrequency: '15分钟' } },
    { id: 'f_forecast_power', tableId: 't_forecast', seq: 2,
      business: { code: 'PREDICT_POWER', nameCn: '预测功率', definition: '预测功率', masterDataId: null, masterDataType: null },
      technical: { type: 'decimal(5,2)', length: 7, isPK: false, isFK: false, qualityRuleIds: [] },
      management: { standardId: 'std_power', securityLevel: 'L2', owner: '运维组', updateFrequency: '15分钟' } },
    { id: 'f_forecast_project', tableId: 't_forecast', seq: 3,
      business: { code: 'PROJECT_ID', nameCn: '所属项目', definition: '所属项目', masterDataId: 'md_project', masterDataType: '项目' },
      technical: { type: 'varchar(32)', length: 32, isPK: false, isFK: true, qualityRuleIds: [] },
      management: { standardId: null, securityLevel: 'L2', owner: '运维组', updateFrequency: '15分钟' } },
    { id: 'f_forecast_accuracy', tableId: 't_forecast', seq: 4,
      business: { code: 'ACCURACY', nameCn: '预测精度', definition: '预测精度', masterDataId: null, masterDataType: null },
      technical: { type: 'decimal(4,2)', length: 6, isPK: false, isFK: false, qualityRuleIds: [] },
      management: { standardId: null, securityLevel: 'L2', owner: '运维组', updateFrequency: '15分钟' } },
    { id: 'f_forecast_model', tableId: 't_forecast', seq: 5,
      business: { code: 'MODEL', nameCn: '算法模型', definition: '算法模型', masterDataId: null, masterDataType: null },
      technical: { type: 'varchar(32)', length: 32, isPK: false, isFK: false, qualityRuleIds: [] },
      management: { standardId: null, securityLevel: 'L2', owner: '运维组', updateFrequency: '15分钟' } },

    // t_spare 备品备件表
    { id: 'f_spare_name', tableId: 't_spare', seq: 1,
      business: { code: 'NAME', nameCn: '备件名称', definition: '备件名称', masterDataId: null, masterDataType: null },
      technical: { type: 'varchar(64)', length: 64, isPK: true, isFK: false, qualityRuleIds: [] },
      management: { standardId: null, securityLevel: 'L2', owner: '备件组', updateFrequency: '每日' } },
    { id: 'f_spare_qty', tableId: 't_spare', seq: 2,
      business: { code: 'QTY', nameCn: '库存数量', definition: '库存数量', masterDataId: null, masterDataType: null },
      technical: { type: 'int', length: 4, isPK: false, isFK: false, qualityRuleIds: ['qr_008'] },
      management: { standardId: null, securityLevel: 'L2', owner: '备件组', updateFrequency: '每日' } },
    { id: 'f_spare_turbine', tableId: 't_spare', seq: 3,
      business: { code: 'TURBINE_ID', nameCn: '适配机型', definition: '适配机型', masterDataId: null, masterDataType: null },
      technical: { type: 'varchar(32)', length: 32, isPK: false, isFK: false, qualityRuleIds: [] },
      management: { standardId: 'std_turbine', securityLevel: 'L2', owner: '备件组', updateFrequency: '每日' } },
    { id: 'f_spare_supplier', tableId: 't_spare', seq: 4,
      business: { code: 'SUPPLIER_ID', nameCn: '供应商', definition: '供应商', masterDataId: 'md_supplier', masterDataType: '供应商' },
      technical: { type: 'varchar(32)', length: 32, isPK: false, isFK: true, qualityRuleIds: [] },
      management: { standardId: null, securityLevel: 'L2', owner: '备件组', updateFrequency: '每日' } },
    { id: 'f_spare_project', tableId: 't_spare', seq: 5,
      business: { code: 'PROJECT_ID', nameCn: '所属项目', definition: '所属项目', masterDataId: 'md_project', masterDataType: '项目' },
      technical: { type: 'varchar(32)', length: 32, isPK: false, isFK: true, qualityRuleIds: [] },
      management: { standardId: null, securityLevel: 'L2', owner: '备件组', updateFrequency: '每日' } },
  ],
  qualityResults: [
    { id: 'qres_app_res', appId: 'app_res', score: 92, dimension: '完整性', issues: [
      { id: 'issue_001', fieldId: 'f_wind_speed', ruleId: 'qr_003', desc: '2026-07 有 3 个 10 分钟区间风速缺失', severity: '警告' },
    ]},
    { id: 'qres_app_ops', appId: 'app_ops', score: 78, dimension: '准确性', issues: [
      { id: 'issue_002', fieldId: 'f_scada_power', ruleId: 'qr_001', desc: '6 台机组有功功率越界（>16MW）', severity: '严重' },
    ]},
  ],
};
export default D;
